name: TestCov
on: [push]

env:
  IMAGE_NAME: netbox-sync-physical-hosts
  NETBOX_ADDRESS: http://test:8000
  NETBOX_TOKEN: 12345
jobs:
  test:
    name: Coverage code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pytest
        pip install pytest-cov
        pip install -r requirements.txt
    - name: Add path
      run: |
        echo "PYTHONPATH=/home/runner/work/netbox-sync-physical-hosts>> $GITHUB_ENV"
        echo "PYTHONPATH=/home/runner/work/netbox-sync-physical-hosts/netbox-sync-physical-hosts>> $GITHUB_ENV
    - name: Generate coverage report
      run: |
        pytest --cov=./ --cov-report=xml
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
